/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TestimonialsRouteImport } from './routes/testimonials'
import { Route as FamilyGrowwRouteImport } from './routes/family-groww'
import { Route as EventsRouteImport } from './routes/events'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as CharanSparshRouteImport } from './routes/charan-sparsh'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'

const TestimonialsRoute = TestimonialsRouteImport.update({
  id: '/testimonials',
  path: '/testimonials',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyGrowwRoute = FamilyGrowwRouteImport.update({
  id: '/family-groww',
  path: '/family-groww',
  getParentRoute: () => rootRouteImport,
} as any)
const EventsRoute = EventsRouteImport.update({
  id: '/events',
  path: '/events',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const CharanSparshRoute = CharanSparshRouteImport.update({
  id: '/charan-sparsh',
  path: '/charan-sparsh',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charan-sparsh': typeof CharanSparshRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/family-groww': typeof FamilyGrowwRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charan-sparsh': typeof CharanSparshRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/family-groww': typeof FamilyGrowwRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/charan-sparsh': typeof CharanSparshRoute
  '/contact': typeof ContactRoute
  '/events': typeof EventsRoute
  '/family-groww': typeof FamilyGrowwRoute
  '/testimonials': typeof TestimonialsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/charan-sparsh'
    | '/contact'
    | '/events'
    | '/family-groww'
    | '/testimonials'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/charan-sparsh'
    | '/contact'
    | '/events'
    | '/family-groww'
    | '/testimonials'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/charan-sparsh'
    | '/contact'
    | '/events'
    | '/family-groww'
    | '/testimonials'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CharanSparshRoute: typeof CharanSparshRoute
  ContactRoute: typeof ContactRoute
  EventsRoute: typeof EventsRoute
  FamilyGrowwRoute: typeof FamilyGrowwRoute
  TestimonialsRoute: typeof TestimonialsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/testimonials': {
      id: '/testimonials'
      path: '/testimonials'
      fullPath: '/testimonials'
      preLoaderRoute: typeof TestimonialsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family-groww': {
      id: '/family-groww'
      path: '/family-groww'
      fullPath: '/family-groww'
      preLoaderRoute: typeof FamilyGrowwRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/events': {
      id: '/events'
      path: '/events'
      fullPath: '/events'
      preLoaderRoute: typeof EventsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/charan-sparsh': {
      id: '/charan-sparsh'
      path: '/charan-sparsh'
      fullPath: '/charan-sparsh'
      preLoaderRoute: typeof CharanSparshRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CharanSparshRoute: CharanSparshRoute,
  ContactRoute: ContactRoute,
  EventsRoute: EventsRoute,
  FamilyGrowwRoute: FamilyGrowwRoute,
  TestimonialsRoute: TestimonialsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
